#образ основан на alpine
FROM alpine:3.11 as alpine
#установка сертификата
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.11
#переменные окружения
ENV GODEBUG netdns=go
ENV DRONE_RUNNER_OS=linux
ENV DRONE_RUNNER_ARCH=amd64
ENV DRONE_RUNNER_PLATFORM=linux/amd64
ENV DRONE_RUNNER_CAPACITY=1
#добавляем папки из билд окружения в образ
ADD release/linux/amd64/drone-agent /bin/
#проверяем конфигурационный файл для выбора служебных имён 
RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
#Копируем локальные файлы из билд контекста
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
#тот данные того кто поддеривает образ
LABEL com.centurylinklabs.watchtower.stop-signal="SIGINT"
#вызывает команду drone-agent во время выполнения контейнера
ENTRYPOINT ["/bin/drone-agent"]

