version: "3"

networks:
        gitea:
                external: false

services:
        server:
                image: gitea/gitea:1.14.2
                container_name: gitea
                environment: 
                        - ER_UID=1000
                        - USER_GID=1000
                        - GITEA__database__DB_TYPE=mysql
                        - GITEA__database__HOST=db:3306
                        - GITEA__database__NAME=gitea
                        - GITEA__database__USER=gitea
                        - GITEA__database__PASSWD=gitea
                restart: always
                networks:
                        - gitea
                volumes:
                        - ./data/gitea:/data
                        - /etc/timezone:/etc/timezone:ro
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - "3000:3000"
                        - "222:22"
                depends_on:
                        - db
        db:
                image: mysql:8
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=gitea
                        - MYSQL_USER=gitea
                        - MYSQL_PASSWORD=gitea
                        - MYSQL_DATABASE=gitea
                networks:
                        - gitea
                volumes:
                        - ./data/mysql:/var/lib/mysql
        drone:
                image: drone/drone:2.0.1
                restart: always
                volumes:
                        - ./data/drone:/var/lib/drone
                ports:
                        - "81:80"
                environment:
                        - DRONE_SERVER_HOST=192.168.0.60:81
                        - DRONE_SERVER_PROTO=http
                        - DRONE_RPC_SECRET=108e640bbc86cac3be5d86d122
                        - DRONE_GITEA_CLIENT_SECRET=Y7DOA_WjhZ1RVwubFC723IErICznW0KFr_SwfgNqBLk=
                        - DRONE_GITEA_SERVER=http://192.168.0.60:80
                        - DRONE_GITEA_CLIENT_ID=65ea003d-4d28-4265-a0b8-64aef3b9f2ed
                        - DRONE_USER_CREATE=username:user123,admin:true 
        drone-agent:
                image: drone/drone-runner-docker:1.6.3
                restart: always
                depends_on:
                        - drone
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                environment:
                        - DRONE_RPC_HOST=drone:80
                        - DRONE_RPC_PROTO=http
                        - DRONE_RPC_SECRET=108e640bbc86cac3be5d86d122
        kanboard:
                image: kanboard/kanboard:v1.2.20
                ports:
                         - "82:80"
                         - "443:443"
                volumes:
                         - ./data/kanboard/kanboard_data:/var/www/app/data
                         - ./data/kanboard/kanboard_plugins:/var/www/app/plugins
                         - ./data/kanboard/kanboard_ssl:/etc/nginx/ssl
                          
                                        



